#!/usr/bin/env python
from PIL import Image
from tqdm import tqdm

import os
import sys
from pathlib import Path


def compress_images(begin_directory: Path, target_directory: Path, quality=30):
    """compress images

    Args:
        begin_directory (Path): begin dir
        target_directory (Path): target image dir
        quality (int, optional):  Defaults to 30/100.
    """

    # images = [file for file in files if file.endswith(("jpg", "png"))]
    images = os.listdir(begin_directory)
    for image in tqdm(images):

        image_begin = str(begin_directory / image)
        img = Image.open(image_begin).convert("RGB")

        if image.endswith(("jpg", "png")):
            image = image[:-4]
        elif image.endswith(("jpeg")):
            image = image[:-5]

        image = image + ".jpg"

        img.save(str(target_directory / image), optimize=True, quality=quality)


if __name__ == "__main__":

    begin_directory = Path.absolute(Path(sys.argv[1]))
    target_directory = Path.absolute(Path(sys.argv[2]))

    compress_images(
        begin_directory=begin_directory, target_directory=target_directory, quality=30
    )

    print("done!")
